fixes #5 - Added method to access loklak search API
loklak/loklak_ruby_api pull request #6
Opened 2017-04-20 05:29 UTC by djmgit

fixed issue #5, now the library contains method to access
loklak search API service.

2017-04-20 13:34 UTC, sudheesh001 requested changes

2017-04-20 13:34 UTC, sudheesh001 commented on lib/loklak.rb
> +    method_path = 'search.json?'
Remove the `?` from here and put it before `query=` That makes more sense than having a query endpoint with a `?` trailing it.

2017-04-20 13:34 UTC, sudheesh001 commented on lib/loklak.rb
> +        method_path += '%20from:' + from_user
Please use ` ` in place of `%20` You can encode the URLs using ruby's libraries

2017-04-20 16:12 UTC, djmgit commented
@sudheesh001 made the changes

2017-04-21 16:30 UTC, daminisatya approved these changes

2017-05-11 03:27 UTC, djmgit commented
@daminisatya @sudheesh001 should I make any other changes in this PR?

2017-05-11 08:51 UTC, sudheesh001 approved these changes

2017-05-12 07:05 UTC, mariobehling commented
Please resolve conflicts.

2017-05-12 11:58 UTC, djmgit commented
@mariobehling resolved conflicts

2017-05-12 12:57 UTC, merged